name: Build and Publish

# INFO: This workflow can't push to the repository
permissions: read-all

# INFO: Run workflow on changes to the sdks
on: 
  push:
  workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        if: startsWith(github.event.head_commit.message, 'release')
        steps:
            - uses: actions/checkout@v3
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: Enable Corepack for Yarn
              run: corepack enable
            - name: Install dependencies
              run: bun install
            - name: Build package
              run: bun run build
            - name: Read NPM Key
              run: |
                  echo 'npmAuthToken: "${{ secrets.NPM_PUBLISH_KEY }}"' >> .yarnrc.yml
            - name: Publish ğŸ‰
              run: yarn publish
